theme = "landing-page-hugo"
baseurl = "http://blueprintanalytics.co.za"
languageCode = "en-us"
title = "Blueprint Analytics"
canonifyUrls = "true"

[params]
    description = "Analyses and training designed for you"
    custom_css = ["css/local.css"]
    googleAnalytics = "UA-71613331-1"

[[params.social]]
    title = "email"
    icon = "envelope"
    url = "mailto:peter.kamerman@gmail.com"

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5
