theme = "landing-page-hugo"
baseurl = "http://blueprintanalytics.co.za"
languageCode = "en-us"
title = "Blueprint Analytics"
canonifyUrls = "true"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    description = "Analyses and training designed for you"
    custom_css = ["css/local.css"]
    googleAnalytics = "UA-71613331-1"

[[params.social]]
    title = "email"
    icon = "envelope"
    url = "mailto:peter.kamerman@gmail.com?subject=Request for information&body=Dear Peter"

[[params.social]]
    title = "Tel: +27 (0)83-415-7448"
    icon = "phone"
    url = "te:+27834157448"

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5
