theme = "landing-page-hugo"
baseurl = "https://www.blueprint-analytics.net"
languageCode = "en-us"
title = "Blueprint Analytics"
canonifyUrls = "true"

[markup.goldmark.renderer]
    unsafe= true

[params]
    description = "Statistical analyses designed for you"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:peter.kamerman@gmail.com"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/painblogR"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/kamermanpr"
[[params.social]]
    title = "linkedin"
    icon = "linkedin"
    url = "http://linkedin.com/in/kamermanpr"
